### ISSUE TITLE
userStory - addProfilePage

### ISSUE THREAD

**Issue by avoesen** [gcode-de/mealwheel#10]
## Value proposition
As a user
I want to have a personal page 
In order to have a overview about my favorite und already cooked recipes
## Description

<img width="413" alt="Bildschirmfoto 2024-03-06 um 19 31 47" src="https://github.com/gcode-de/mealwheel/assets/155978924/ec05408a-514f-48e6-929f-bf80113af9fc">

## Acceptance criteria
- the user can navigate to their own profile page.
- the page displays links to settings, an overview of favorites, and a page for recipes that have been cooked.
- it also displays the user's name and their picture.

## Tasks
- [ ] add a profile icon to the navigation bar, which leads to the new `profile.js` page.
- [ ] on the profile page, add a link to the `settings.js` page.
- [ ] create a component that displays the user's image and a welcome message.
- [ ] add two links, one for the favorite recipes and another for an overview of recipes that have been cooked.
- [ ] delete the link for favorites in the nav bar.
