### ISSUE TITLE
userStory - rename collections

### ISSUE THREAD

**Issue by avoesen** [gcode-de/mealwheel#100]
## Value proposition
As a user,
I want to be able to rename collections in the database,
In order to maintain better organization of my data and adhere to naming conventions.
## Description
Currently, collections in the database might have names that are not clear, outdated, or don't follow a consistent naming scheme. Renaming collections would allow me to:

Improve clarity and understanding of the data stored in each collection.
Organize my data more effectively for easier retrieval and management.
Adhere to established naming conventions for consistency within the database.

## Acceptance criteria
- the user can see a list of all collections
- Each collection name is displayed clearly.
- the user select a collection from the list.
- the user enter a new name for the selected collection.
- Upon confirmation, the system renames the collection in the database.
- The system displays a confirmation message indicating the successful renaming.
- The list of collections is updated to reflect the new name. 
## Tasks
- [ ] switch to `collections.js` and add logic to isEditing mode. 
- [ ] the p-tag should switch to input field, which consider the default value of the collection name
- [ ] after changing name you can confirm with clicking next to the field 
- [ ] you still have to close and confirm the editing mode
