### ISSUE TITLE
userStory - community rating

### ISSUE THREAD

**Issue by avoesen** [gcode-de/mealwheel#101]
## Value proposition
As a user
I want to see the rating for recipes and collections
In order to find inspiration and chose the best option
## Acceptance criteria
- [ ] the number of likes is displayed on the recipe cards on the home page
- [ ] the number changes, when a user adds a recipe to his favorites or removes it

## Tasks
- [x] create an API route to change the number of likes for a recipe, receiving 1 or -1
- [x] fetch the route when "toggleIsFavorite" is called according to new like state
- [x] trigger mutate for recipe(s)
- [x] add display for number of likes in mealcard and details page
- [x] style display for number of likes
- [ ] move recipes fetching with filters to _app.js

**Comment by stellanw** [comment]
Looks good!
