### ISSUE TITLE
userStory - addFriends

### ISSUE THREAD

**Issue by avoesen** [gcode-de/mealwheel#107]
## Value proposition
As a user
I want to add friends to my community
In order to see the recipes of my friends
## Acceptance criteria
- the other user should have the option to accept or decline the friend request
- If the request is accepted, the user should be automatically added to my friends list, and I should receive a notification
- If the request is declined, I should receive a corresponding notification
- I should be able to view the list of my friends and see their recipes
- there should be a way to remove friends from my friends list if desired

## Tasks
- [ ] implement a function to the "Follow" button which save notification request in the db of the requested user
- [ ] the notification request should renders on the `profile/index.js` 
- [ ] the request can be accepted or rejected by the user
- [ ] the unfollow button should delete the connection in db

**Comment by F-Kirchhoff** [comment]
Hey,
this looks like a really complex user story and is probably too much for just one. Please restructure this user story into separate elements: 
- create the friends page
- search for friends in the db
- sending a friend request with respective updates on both side
- removing a friend / unfollowing him.
Please add a wireframe to each user story then.
