### ISSUE TITLE
userStory - showCommunity

### ISSUE THREAD

**Issue by avoesen** [gcode-de/mealwheel#108]
## Value proposition
As a user, 
I want to be able to browse a list of all users 
in order to easily find and connect with people
## Acceptance criteria
- I should be able to search for users by browsing a list of users

## Tasks
- [ ] create new page `profile/community.js`, it renders a "FriendCard" which displays the profile picture, the name of each user
- [ ] add api/route to fetch all users
- [ ] add in `profile/index.js` a "Community" Link which links to community page

**Comment by F-Kirchhoff** [comment]
Hey Anna,
thanks for chaning the user story. You could improve the user story by adding a wireframe and some acceptance criteria, but I understand that you want to finish this feature in time, so lets skip it.
