### ISSUE TITLE
userStory - customizeMealsPerDay

### ISSUE THREAD

**Issue by avoesen** [gcode-de/mealwheel#11]
## Value proposition
As a user
I want to be able to adjust the number of daily meals as default
In order to plan also the meal for breakfast, lunch or even my snacks.
## Description
 
<img width="273" alt="Bildschirmfoto 2024-03-07 um 07 54 54" src="https://github.com/gcode-de/mealwheel/assets/155978924/811c013c-2fad-46e9-a900-75b31a039dcc">

## Acceptance criteria
- [ ] the user can set the number of meals per day
- [ ] the recipes which renders on the `plan.js` will update 
- [ ] all recipes need an extra tag which accommodated the mealType
## Tasks
- [ ]
