### ISSUE TITLE
userStory - showAllRecipesOfUser

### ISSUE THREAD

**Issue by avoesen** [gcode-de/mealwheel#111]
## Value proposition
As a user
I want to be able to view all recipes created by a specific user
In order to explore their culinary creations and potentially find inspiration for my own cooking endeavors.
## Description
The user desires the capability to access and browse through all recipes associated with a particular user. This feature will allow the user to discover a comprehensive list of recipes authored by the selected user, enabling them to explore various dishes and potentially replicate them in their own cooking endeavors.

## Acceptance criteria
- the app should provide an option for users to access the "Show All Recipes of User" feature
- upon selecting the option to view all recipes of a user, the user should be presented with a list of recipes associated with that specific user
- each recipe entry in the list should display essential details such as the recipe title, image (if available), and any other relevant information
- the user should have the ability to click on any recipe from the list to view its complete details, including ingredients, instructions, and other pertinent information
## Tasks
- [ ]  change `myRecipes.js`and just show the recipes of the user
- [ ] design and implement the user interface for presenting the list of recipes associated with the selected user
- [ ] ensure seamless navigation to the detailed view of each recipe upon user selection.
- [ ] implement the "schmecko" function

**Comment by gcode-de** [comment]
We can reuse this existing fetch from the myRecipes.js for this:

const {
    data: myRecipes,
    error: recipesError,
    isLoading: recipesIsLoading,
  } = useSWR(`/api/recipes?author=${user?._id}`);

**Comment by Krischan-Klug** [comment]
It would be cool if you could still see who created the recipes and therefore be able to quickly get to the user page.
