### ISSUE TITLE
userStory - addFeed

### ISSUE THREAD

**Issue by avoesen** [gcode-de/mealwheel#114]
## Value proposition
As a user
I want to ...
In order to ...
## Description
<img width="397" alt="user story 14" src="https://github.com/gcode-de/mealwheel/assets/155978924/a62e22d9-7f3a-49bb-a9bc-029846d25ea4">

## Acceptance criteria
- [ ] 
## Tasks
- [ ] change Navbar and switch "entdecken" to the third icon 
- [ ] delete the "favorites" link
- [ ] add go back chevron on favorites page
- [ ] add "Feed" to first position, it should just renders recipes of your friends
