### ISSUE TITLE
userStory - createNewWeeklyRecipePlan-Button

### ISSUE THREAD

**Issue by Bjoern-Jentschke** [gcode-de/mealwheel#17]
## Value proposition
As a user
I want to generate a weekly recipe plan in which I can tell how many random recipes I want
In order to gather optimal ideas for my weekly recipe plan.
## Description
 

![Image](https://github.com/gcode-de/mealwheel/assets/155737121/46881717-d114-4224-a7dc-b891ea789de4)

## Acceptance criteria
- the user can set the number of random recipes that should be generated for the week
- the user has control how many of his own recipes will be displayed
- there is a create button
- after clicking the create button and setting the number of random recipes the recipes are distributed into the days
- the days that are disabled or already have a recipe in it, wont be filled with another recipe
-
## Tasks
- [ ] add the create button with a on click functionality
- [ ] add the logic that the days that are empty are filled with a random recipe
- [ ] add the logic that the distribution of random and own recipes follows the settings on how many random recipes should be in the weekly recipe plan
- [ ] add the logic that enabled days should not be filled with another recipe
