### ISSUE TITLE
userStory_02 - DetailsPage

### ISSUE THREAD

**Issue by Bjoern-Jentschke** [gcode-de/mealwheel#2]
## Value proposition
As a user
I want to click on one of the recipes
In order to see more details about it.
## Description

![Image](https://github.com/gcode-de/mealwheel/assets/155737121/c66adb29-9c95-49c6-8201-f12d2d752d18)

## Acceptance criteria
- [ ] On the details page, there is one recipe displayed
- [ ] Each recipe detail page includes the following details:
  - The name of the recipe
  - The poster image of the recipe
  - the tags of the recipe
  - the ingredients of the recipe
  - instruction on how to prepare the recipe
  - the nutrition stats of the recipe
- [ ] If there is an issue loading the recipe data from the source, an error message is displayed to the user
- [ ] The recipe is vertically scrollable
## Tasks
- create the details page
- fetch the recipes by id from the api/database
- select the targeted data
- style the details page

**Comment by MerleMak** [comment]
amazing!!

**Comment by Bjoern-Jentschke** [comment]
Thank you @MerleMak !
