### ISSUE TITLE
userStory - scrollToTopButton

### ISSUE THREAD

**Issue by Bjoern-Jentschke** [gcode-de/mealwheel#24]
## Value proposition
As a user
I want to be able to navigate with one click to the top of the overview page after scrolling down
In order to navigate directly back to the top of the overview page.
## Description
 

![Image](https://github.com/gcode-de/mealwheel/assets/155737121/24e0e96f-fc31-424b-b6e7-b666b81d46cf)

## Acceptance criteria
- [ ] the user can click on the scroll to top button
- [ ] after clicking the scroll to top button, the side scrolls to the top of the overview page
- [ ] the scroll to top-button appears after scrolling down on the overview page
## Tasks
- [ ] add the scroll to top button
- [ ] add a svg to the scroll to top button
- [ ] add the scroll to top functionality to the button
