### ISSUE TITLE
userStory - editProfile

### ISSUE THREAD

**Issue by avoesen** [gcode-de/mealwheel#26]
## Value proposition
As a user
I want to edit my profile
In order to feel more at home in the app
## Description
<img width="285" alt="Bildschirmfoto 2024-03-11 um 10 09 30" src="https://github.com/gcode-de/mealwheel/assets/155978924/c019fcbd-7ccc-4e06-a079-d4da7752b3e7">

## Acceptance criteria
-User can upload/change a profile picture
-user can add/change a username

## Tasks
- [ ] create design
- [ ] create profile image function
- [ ] create function to add/change username
- [ ] create fallback if username or image are not provided: check in auth-session, then use standard values
