### ISSUE TITLE
userStory - designToasts

### ISSUE THREAD

**Issue by avoesen** [gcode-de/mealwheel#29]
## Value proposition
As a user
I want to recieve a confirmation after setting a date for a certain recipe
In order to be assured that the recipe is successful set for the targeted date.

## Description
<img width="286" alt="Bildschirmfoto 2024-03-11 um 10 09 49" src="https://github.com/gcode-de/mealwheel/assets/155978924/2c3d19e9-0dc1-47e1-8ada-b8b54ba1dce4">

## Acceptance criteria
- After assigning a recipe for a special date, on the detailPage there is a toast appearing that assures the user a successful adding

## Tasks
- [x] add a toast as a pop up after the recipe is set for a certain day on the detailPage
- [x] add the toast for delete a recipe
- [x] add the toast for edit a recipe
- [x] add the toast for add a recipe
- [x] add the toast for saveInShopping
