### ISSUE TITLE
userStory - deleteRecipeOnlyAuthor

### ISSUE THREAD

**Issue by avoesen** [gcode-de/mealwheel#30]
## Value proposition
As a user
I want to be able to delete my own recipes
In order achieve inner peace and a clear state of mind.
## Description

![Image](https://github.com/gcode-de/mealwheel/assets/155737121/fbd5f192-5664-41ce-9ef1-0f96cb85acf3)

## Acceptance criteria
- if the user is the author of the recipe, there is a delete button displayed on the detail page
- if the user clicks the button the recipe is deleted

## Tasks
- [ ] add a delete button to the recipe detail page
- [ ] add delete functionality to the delete button
- [ ] display button if user is author
