### ISSUE TITLE
userStory - deleteImagesCloudinary

### ISSUE THREAD

**Issue by Bjoern-Jentschke** [gcode-de/mealwheel#34]
## Value proposition
As a developer
I want that  after replacing an image the old image is deleted in cloudinary and the new image is displayed instead
In order to save cloudinary storage space
## Description
 

![Image](https://github.com/gcode-de/mealwheel/assets/155737121/0a80ecd2-84b7-41ed-bad5-79f920c78850)

## Acceptance criteria
- [ ] after a image is changed, the old image in cloudinary is removed from the memory space
- [ ] the new image is displayed and saved

## Tasks
- [ ] after editing the recipe and adding a new image : remove the old image on cloudinary and add instead the new image on both the recipe details page and the user profile page
