### ISSUE TITLE
userStory - clearShoppingList

### ISSUE THREAD

**Issue by avoesen** [gcode-de/mealwheel#43]
## Value proposition
As a user, 
I desire the ability to remove items from the shopping list to enhance my flexibility in meal planning.

## Description
<img width="290" alt="Bildschirmfoto 2024-03-12 um 17 39 26" src="https://github.com/gcode-de/mealwheel/assets/155978924/f1d4f0f9-55e4-4c61-9cdc-3512f8cecac9">

## Acceptance criteria
- users can delete the entire content of the shopping list
- ingredients should disappear after being checked
## Tasks
- [x] add a delete button on `shopping.js`
- [x] implement a function to clear the entire shopping list and bind it to the button
- [x]  ensure that checked ingredients disappear after 10 seconds
