### ISSUE TITLE
userStory - addNewRecipe - imageAdding

### ISSUE THREAD

**Issue by Bjoern-Jentschke** [gcode-de/mealwheel#5]
## Value proposition
As a user
I want to add a recipe picture while adding a new recipe
In order to have a preview on how the recipe should look like.
## Description

![Image](https://github.com/gcode-de/mealwheel/assets/155737121/712a5d3e-5b0f-40b4-88cb-3d4020cd64f9)

## Acceptance criteria
- in the addNewRecipe form, there is a button to add a image
- the user can click the button and then upload the picture
- the picture is then displayed on the added recipe

## Tasks
- [ ] create the button add new recipe in the form field
- [ ] adding the upload function to the button in the form field
- [ ] using cloudinary to host the images and deliver them to the client

**Comment by gcode-de** [comment]
top
