### ISSUE TITLE
userStory - addCollections

### ISSUE THREAD

**Issue by avoesen** [gcode-de/mealwheel#50]
## Value proposition
As a user, 
I would like to organize my recipes into collections 
in order to have a better overview.
## Description
<img width="227" alt="Bildschirmfoto 2024-03-13 um 15 54 24" src="https://github.com/gcode-de/mealwheel/assets/155978924/3d3fa699-3f8f-411a-a08a-e66772388ff1">

## Acceptance criteria
- from my user dashboard, I can access the "My Recipes" section and browse through my collections or cookbooks
- additionally, I have the option to create a new collection and select recipes to include in it
## Tasks
- [ ] create a link on the "My Recipes" page leading to a new page named `collections.js`
- [ ] introduce a collections array within the db/user. This array should store the name of the collection and all the recipe IDs it contains
- [ ] implement an "Add" button on the `collections.js` page to create a new key in the collections array
- [ ] include a "Save" button on the `recipe/index.js`. This button should store the ID of the selected recipe in a collection
- [ ] render all recipes that contains on the `collection.js`
