### ISSUE TITLE
userStory - search and sort function

### ISSUE THREAD

**Issue by gcode-de** [gcode-de/mealwheel#52]
## Value proposition
As a user
I want to search for recipe titles and chose a way to sort the results
In order to find recipes quicker
## Description
![Bildschirmfoto 2024-03-15 um 10 42 41](https://github.com/gcode-de/mealwheel/assets/102192231/e2f4bc2a-027a-4d75-803d-3b092d15317c)

## Acceptance criteria
- [ ] a functioning search bar is integrated into the filter section that updates the search results after every keystroke
- [ ] a way to sort the (filtered) search results is implemented

## Tasks
- [ ] create search bar
- [ ] add search term to url and/or API query
- [ ] handle search query in API to query recipes from MongoDB
- [ ] create sort section
- [ ] add sorting method to url and/or API query
- [ ] handle sorting method in API to query recipes from MongoDB
