### ISSUE TITLE
userStory - addNotes

### ISSUE THREAD

**Issue by avoesen** [gcode-de/mealwheel#55]
## Value proposition
As a user
I want to add notes to a recipe
In order to memorize the thoughts I had when preparing the recipe or judging the recipe.
## Description
<img width="194" alt="Bildschirmfoto 2024-03-15 um 14 39 37" src="https://github.com/gcode-de/mealwheel/assets/155978924/a68ae8ba-2444-44a4-834a-0021972629bc">

## Acceptance criteria
- on the detail page the user can add note in a textarea
- the notes are then saved and the user can see them displayed on the detail page
- the user can edit the notes
## Tasks
- [ ] add a textarea to the detail page
- [ ] add a save functionality to the textarea in order to save the note
- [ ] add a post, edit and delete path so the author of the note can see the note displayed, delete and edit it
