### ISSUE TITLE
userStory - General Styling

### ISSUE THREAD

**Issue by avoesen** [gcode-de/mealwheel#56]
## Value proposition
As a user 
I want to be able to use the planner intuitively 
in order I can easily understand its functionality and utilize it effectively
## Description
<img width="190" alt="Bildschirmfoto 2024-03-15 um 14 39 42" src="https://github.com/gcode-de/mealwheel/assets/155978924/26b83da7-c335-4aca-9e8c-bbeac4f46e6a">

## Acceptance criteria
- 
## Tasks
Anna:
- [x] Detail Page: change the IconButton to hasCooked, isFavorite and Menu. In Menu there should be edit, saveInCalender and saveInCollection
 - [x] Toasts: show Toast after logout, shorten display duration
- [x] Settings-page: change colors of enableWeekdays to lightgrey and darkgrey like tags
- [x] Profile-page: change layout to grid and make feedback one of them, add subtle impressum-link to the bottom
- [x]  style collections area when user has no collections, change book+text alignment

Samuel:
- [x] reduce gap-out to 1rem
- [x] create impressum page
- [x] set correct font page wide: Archivo + Header-Font (Fira Sans)
- [x] Mealcard: shorten recipe titles with (...) in mealcard if necessarry
- [x] change highlight-color to Senf
- [x] Header: delete emoji and reduce height
- [x] fix safari (mobile) styling, (input fields, select-options, all buttons..., youtube-link)
- [x] create nextauth error page
- [x] add mealtype in Recipe Form and Filters

Björn:
- [ ] update week planner: replace power icon with toggle, remove X-icon, disabling a day should delete the recipe assignment, move reload-button in mealcard next to setServings and replace icon with magic wand, put slider in "filter-menü" and add text to describe it better
