### ISSUE TITLE
userStory - shareRecipe

### ISSUE THREAD

**Issue by avoesen** [gcode-de/mealwheel#59]
## Value proposition
As a user
I want to share a recipe 
in order to share it with others and see their reactions
## Description

<img width="191" alt="Bildschirmfoto 2024-03-15 um 14 40 27" src="https://github.com/gcode-de/mealwheel/assets/155978924/5151d6e4-3393-445b-a126-983766fc9f7d">

you can choose if you want share a link or in IG Story. It will render a recipe card, which fits the IG Dimensions.

## Acceptance criteria
- implement recipe sharing functionality
- ensure shared recipes are visible to other users
- enable users to interact with shared recipes by saving, commenting, or rating them
- provide users with the ability to view reactions and feedback from other users on shared recipes

## Tasks
- [ ] develop UI components for sharing recipes
- [ ] implement backend logic to handle recipe sharing and interactions
- [ ] integrate functionality to display reactions and feedback on shared recipes
- [ ] test and refine the recipe sharing feature to ensure seamless user experience
