### ISSUE TITLE
userStory - shareCollection

### ISSUE THREAD

**Issue by avoesen** [gcode-de/mealwheel#60]
## Value proposition
As a user 
I want to share a collection of recipes 
in order to inspire and collaborate with others
## Description
<img width="189" alt="Bildschirmfoto 2024-03-15 um 14 40 32" src="https://github.com/gcode-de/mealwheel/assets/155978924/f564e61d-c065-47c9-9e0e-ae359dc2d0e0">

## Acceptance criteria
- implement functionality to create and share collections of recipes
- ensure shared collections are visible to other users
- enable users to interact with shared collections by saving, commenting, or rating them
- provide users with the ability to view reactions and feedback from other users on shared collections

## Tasks
- [ ] add share button to the dynamic route at collections
- [ ] implement backend logic to handle collection creation and sharing
- [ ] integrate functionality to display reactions and feedback on shared collections
