### ISSUE TITLE
userStory - addCategoriesShoppingList

### ISSUE THREAD

**Issue by avoesen** [gcode-de/mealwheel#63]
## Value proposition
As a User,
I want my shopping list items to be categorized,
to be able to quickly navigate and efficiently shop.
## Description
<img width="191" alt="Bildschirmfoto 2024-03-15 um 14 40 04" src="https://github.com/gcode-de/mealwheel/assets/155978924/aa366941-da63-4eb5-94a5-b2a6122f6667">

## Acceptance criteria
- when the user creates the shopping list, all items are automatically grouped into categories
- the categories are displayed in the shopping list
- the items of the shopping list are grouped automatically into the categories (after button click)
## Tasks
- [x] set up new data structure wit categories in DB Schema
- [x] change function in plan to add items to new data structure
- [x] change existing component to display items from new data structure
- [x] change existing function to modify item
- [x] change existing function to consolidate items
- [x] change existing function to check off item
- [x] change existing function to add item
- [x] fix option to click outside of item to save current edit status
- [x] add OpenAI Library and API Route
- [x] add and style button so trigger sorting function
- [x] create function to get categories for items and save them to DB

**Comment by NikRoe** [comment]
Hi there,

how about this VP:
As a User,
I want my shopping list items to be categorized,
to be able to quickly navigate and efficiently shop.

Apart from that, nicely done (and thus approved, but still change the VP, please) ✌

**Comment by Bjoern-Jentschke** [comment]
Thank you for the draft!! Done and dusted✌️
