### ISSUE TITLE
userStory - deleteRecipesFromCollections

### ISSUE THREAD

**Issue by avoesen** [gcode-de/mealwheel#78]
## Value proposition
As a user 
I want to delete recipes from my collections 
in order to manage my collections more effectively.

## Acceptance criteria
- The menu component from Notes.js should be successfully integrated into collections/index.js
- the functionality of the menu should remain consistent after refactoring
- Each card in the collections view should contain the menu component
- the menu should include a "delete from collection" button for each card
- clicking on the "delete from collection" button should trigger the appropriate action
- upon clicking the "delete from collection" button, a modal should be displayed
- the modal should provide options to confirm or cancel the deletion
- confirming the deletion should remove the item from the collection, while canceling it should close the modal without making any changes
- If there are no collections available, a "add new collection" button should be displayed in 
- Clicking on the "add new collection" button should trigger the appropriate action to create a new collection
## Tasks
- [ ] refactor the menu from the `Notes.js` component to be used in `collections/index.js`
- [ ] Add the menu to each card; the menu should include the "delete from collection" button
- [ ] if the "delete from collection" button is clicked, a modal should appear to confirm the deletion or cancel it
- [ ] in `myRecipes.js` add the "add new collection" button if no collections are available
