### ISSUE TITLE
userStory - editRecipeForm

### ISSUE THREAD

**Issue by avoesen** [gcode-de/mealwheel#79]
## Value proposition
As a user
I want to chose the number of servings when creating a recipe
In order to have the current amount of ingredients later.

## Description
This feature lets users set the number of servings for recipes, adjusting ingredient amounts for accurate meal planning. Servings can be specified during recipe creation/editing and are reflected in recipe details and when assigning recipes to calendar days. A loading spinner is shown during image uploads, enhancing user experience. This improvement offers users precise control over meal quantities, making preparation more efficient and tailored to their needs.

## Acceptance criteria
- [ ] user can specify the number of servings while creating/editing a recipe
- [ ] recipe detail pages show the number of servings set by the creator if not chosen otherwise by user
- [ ] ingredients in details pages are shown according tho set number of servings
- [ ] manually assigning a recipe to a calendar day includes the chosen number of servings
- [ ] also when uploading an image to a recipe a loading spinner is shown while the upload is in progess

## Tasks
- [ ] add option to chose no. of servings to recipe form
- [ ] add defaultNumberOfServings-property to database schema for recipes
- [ ] add option to chose no. of servings to recipe details page and set them in state (also push to URL in browser?)
- [ ] update logic to include no. of servings when manually assigning a recipe to a date
- [ ] modify details page to show ingredients according to set serving size
- [ ] add image loading spinner from profile page to recipe form
