### ISSUE TITLE
userStory - use optimistic updates

### ISSUE THREAD

**Issue by gcode-de** [gcode-de/mealwheel#87]
## Value proposition
As a user
I want to see updates more fluently
In order to have a UX with less friction

## Acceptance criteria
- [ ] UI responds faster to changes like toggling isFavorite oder Drag'n'Drop in the week planner
## Tasks
- [ ] Implement optimistic updates in updateUserInDb.js
- [ ] Fix any related issues
