### ISSUE TITLE
US: Bug fixing

### ISSUE THREAD

**Issue by gcode-de** [gcode-de/mealwheel#92]
## Value proposition
As a developer
I want to fix some bugs
In order to kepp my app running well

## Tasks
- [x] fix recipes API for user that are not logged in
- [x] Logout-Button fehlt
- [x] Navbar passt sich im ausgeloggten zustand noch nicht an, wenn man auf der Login-Seite ist
- [x] Überschrift in Login seite ist falsch geschrieben
- [ ] Das Bild kann nach Anmeldung mit Google im Login Bereich nicht verändert werden

**Comment by mazzelman** [comment]
LGTM - but you switched the language to german :)
